// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/job.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求参数：Master 发过来的
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobHandler    string                 `protobuf:"bytes,1,opt,name=job_handler,json=jobHandler,proto3" json:"job_handler,omitempty"` // 任务名称 (比如 "clean_order")
	JobParams     string                 `protobuf:"bytes,2,opt,name=job_params,json=jobParams,proto3" json:"job_params,omitempty"`    // 任务参数 (比如 "date=2026-01-01")
	JobId         int64                  `protobuf:"varint,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`               // 任务ID，方便记日志
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_proto_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_job_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetJobHandler() string {
	if x != nil {
		return x.JobHandler
	}
	return ""
}

func (x *ExecuteRequest) GetJobParams() string {
	if x != nil {
		return x.JobParams
	}
	return ""
}

func (x *ExecuteRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

// 响应参数：Worker 返回的
type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`          // 错误信息或执行结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_proto_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_job_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_proto_job_proto protoreflect.FileDescriptor

const file_api_proto_job_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/job.proto\x12\x05proto\"g\n" +
	"\x0eExecuteRequest\x12\x1f\n" +
	"\vjob_handler\x18\x01 \x01(\tR\n" +
	"jobHandler\x12\x1d\n" +
	"\n" +
	"job_params\x18\x02 \x01(\tR\tjobParams\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\x03R\x05jobId\"=\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2H\n" +
	"\tJobWorker\x12;\n" +
	"\n" +
	"ExecuteJob\x12\x15.proto.ExecuteRequest\x1a\x16.proto.ExecuteResponseB\x15Z\x13go-chrono/api/protob\x06proto3"

var (
	file_api_proto_job_proto_rawDescOnce sync.Once
	file_api_proto_job_proto_rawDescData []byte
)

func file_api_proto_job_proto_rawDescGZIP() []byte {
	file_api_proto_job_proto_rawDescOnce.Do(func() {
		file_api_proto_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_job_proto_rawDesc), len(file_api_proto_job_proto_rawDesc)))
	})
	return file_api_proto_job_proto_rawDescData
}

var file_api_proto_job_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_job_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: proto.ExecuteRequest
	(*ExecuteResponse)(nil), // 1: proto.ExecuteResponse
}
var file_api_proto_job_proto_depIdxs = []int32{
	0, // 0: proto.JobWorker.ExecuteJob:input_type -> proto.ExecuteRequest
	1, // 1: proto.JobWorker.ExecuteJob:output_type -> proto.ExecuteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_job_proto_init() }
func file_api_proto_job_proto_init() {
	if File_api_proto_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_job_proto_rawDesc), len(file_api_proto_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_job_proto_goTypes,
		DependencyIndexes: file_api_proto_job_proto_depIdxs,
		MessageInfos:      file_api_proto_job_proto_msgTypes,
	}.Build()
	File_api_proto_job_proto = out.File
	file_api_proto_job_proto_goTypes = nil
	file_api_proto_job_proto_depIdxs = nil
}
